### ISSUE TITLE
Error: Missing "component" object in the Cypress config object

### ISSUE THREAD

**Issue by Kprachwani** [bahmutov/find-cypress-specs#254]
Hello @bahmutov 
Good day!

This is great plugin, thanks much!
I am getting below error
**$ npx find-cypress-specs --test-counts
D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:153
    throw new Error(`Missing "${type}" object in the Cypress config object`)
    ^**

**Error: Missing "component" object in the Cypress config object**
    at findCypressSpecsV10 (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:153:11)
    at findCypressSpecs (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:290:19)
    at getSpecs (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:253:10)
    at getTestCounts (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\tests-counts.js:13:26)
    at Object.<anonymous> (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\bin\find.js:80:32)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1

Here is the specPattern I have for cypress config

 e2e: {
    specPattern: "e2e/integration/module1/submodule1/*.spec.ts",
   ......
}

Could you please help me ?

**Comment by bahmutov** [comment]
Can you run with debug logs enabled and provide the logs?Sent from my iPhoneOn Apr 12, 2024, at 18:39, Kanchan Prachwani ***@***.***> wrote:﻿
Hello @bahmutov
Good day!
This is great plugin, thanks much!
I am getting below error
$ npx find-cypress-specs --test-counts
D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:153
throw new Error(Missing "${type}" object in the Cypress config object)
^
Error: Missing "component" object in the Cypress config object
at findCypressSpecsV10 (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:153:11)
at findCypressSpecs (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:290:19)
at getSpecs (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\index.js:253:10)
at getTestCounts (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\src\tests-counts.js:13:26)
at Object. (D:\Dev\ogt\ogt-ui_tests\node_modules\find-cypress-specs\bin\find.js:80:32)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:23:47
Node.js v18.17.1
Here is the specPattern I have for cypress config
e2e: {
specPattern: "e2e/integration///*.spec.ts",
......
}
Could you please help me ?

**Comment by bahmutov** [comment]
Closing as not having enough information
